global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'monitoring-system'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager.mahabubsany.com
      scheme: https

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.mahabubsany.com']